package com.kmurawska.designpatterns.strategy;

public enum Ingredient {
    CELANDINE, DROWNER_BRAIN, DWARVEN_SPIRIT, ARACHAS_VENOM, VERBENA, GHOULS_BLOOD, SEWANT_MUSHROOMS, WHITE_MYRTLE_PETALS, GOLEMS_HEART
}
